### ISSUE TITLE
Latest version does not work with type-providers / non-JSON-schema-based route definitions

### ISSUE THREAD

**Issue by chrisbenincasa** [ShogunPanda/fastify-print-routes#6]
The [new feature](https://github.com/ShogunPanda/fastify-print-routes/commit/07b569d2851d5f9a1708807832275e4d52dea015) to print query strings assumes that the schema definitions for a route are done with JSON schema and thus has a field called `properties`. 

This breaks with non-JSON-schema based [Type-Providers](https://fastify.dev/docs/latest/Reference/Type-Providers/) . In my case, I am using the Zod type provider (https://github.com/turkerdev/fastify-type-provider-zod), where Zod schemas are passed directly into the route `schema` field. 

With the code assuming the presence of a `properties` field, the call to enumerate using `Object.keys` fails since that does not exist on the Zod type. Printing the routes throws an exception, the `done` callback is never called on the `onReady` hook and the entire server breaks.

Perhaps including the routes should be an option? Or at the very least exceptions in `printRoutes` can be handled so that the server doesn't break if that call fails. It's probably out of scope / impossible to handle every implementation of schema providers within this plugin.

Example stack:
```
TypeError: Cannot convert undefined or null to object          
    at Function.keys (<anonymous>)                    
    at printRoutes (file:///home/christian/Code/tunarr/node_modules/.pnpm/fastify-print-routes@3.1.1/node_modules/fastify-print-routes/dist/index.js:82:43)
    at Object.<anonymous> (file:///home/christian/Code/tunarr/node_modules/.pnpm/fastify-print-routes@3.1.1/node_modules/fastify-print-routes/dist/index.js:131:13)                          
    at /home/christian/Code/tunarr/node_modules/.pnpm/fastify@4.26.2/node_modules/fastify/lib/hooks.js:158:14                 
    at _encapsulateThreeParam (/home/christian/Code/tunarr/node_modules/.pnpm/avvio@8.3.0/node_modules/avvio/boot.js:589:7)   
    at Boot.timeoutCall (/home/christian/Code/tunarr/node_modules/.pnpm/avvio@8.3.0/node_modules/avvio/boot.js:485:5)         
    at Boot.callWithCbOrNextTick (/home/christian/Code/tunarr/node_modules/.pnpm/avvio@8.3.0/node_modules/avvio/boot.js:467:19)                                                              
...
```

**Comment by dam6pl** [comment]
@ShogunPanda any update on this? Same problem here.

**Comment by ShogunPanda** [comment]
Hi! I created the `querystring` option (enabled by default) in the release [v3.2.0](https://github.com/ShogunPanda/fastify-print-routes/releases/tag/v3.2.0).

Closing for now. Please reopen if it doesn't solve your problem.

**Comment by chrisbenincasa** [comment]
Thanks for the fix! I’ll try it out
