### ISSUE TITLE
Plugin crashes when route includes zod schema with querystring

### ISSUE THREAD

**Issue by ollebergkvist** [ShogunPanda/fastify-print-routes#7]
`21:47:30 UTC error: Cannot convert undefined or null to object
 xTypeError 500: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at printRoutes (file://./node_modules/.pnpm/fastify-print-routes@3.2.0/node_modules/fastify-print-routes/dist/index.js:82:47)
    at Object.<anonymous> (file://./node_modules/.pnpm/fastify-print-routes@3.2.0/node_modules/fastify-print-routes/dist/index.js:132:9)
    at ./node_modules/.pnpm/fastify@4.27.0/node_modules/fastify/lib/hooks.js:158:14
    at _encapsulateThreeParam (./node_modules/.pnpm/avvio@8.3.0/node_modules/avvio/boot.js:589:7)
    at Boot.timeoutCall (./node_modules/.pnpm/avvio@8.3.0/node_modules/avvio/boot.js:485:5)
    at Boot.callWithCbOrNextTick (./node_modules/.pnpm/avvio@8.3.0/node_modules/avvio/boot.js:467:19)
    at Task.release (./node_modules/.pnpm/fastq@1.17.1/node_modules/fastq/queue.js:171:16)
    at worked (./node_modules/.pnpm/fastq@1.17.1/node_modules/fastq/queue.js:223:10)
    at Boot.timeoutCb (./node_modules/.pnpm/avvio@8.3.0/node_modules/avvio/boot.js:494:7)`

It works with body, but not querystring.

    
![Screenshot 2024-07-29 at 14 51 23](https://github.com/user-attachments/assets/42f93467-bda8-4b81-94f2-01aeea8416d2)

**Comment by ShogunPanda** [comment]
Can you please provide me a reproducible repro so I can fix this?

**Comment by ollebergkvist** [comment]
@ShogunPanda Sorry for the delay here, I didn't have the time to revise this until today.

I created a minimal reproducible example here:
https://github.com/ollebergkvist/fastify-print-routes-example

Many thanks in advance 🙏

**Comment by ShogunPanda** [comment]
This has been fixed in 4.0.0, which now supports zod.
